# Academic Profile Website
# Site settings

name: Yueyang Pan 「潘樾阳」
title: Yueyang Pan's Website
position: Ph.D. Candidate
department: EDIC Computer and Communication Sciences
department_url: "https://www.epfl.ch/education/phd/edic-computer-and-communication-sciences/"
institution: École Polytechnique Fédérale de Lausanne (EPFL)
institution_url: "https://www.epfl.ch/en/"
email: yueyang.pan@epfl.ch
description: >- # this means to ignore newlines until "baseurl:"
  This is the personal website of Yueyang Pan
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://panjason.github.io" # the base hostname & protocol for your site, e.g. http://example.com
office: "Office: INN 212, EPFL, Lausanne, Vaud, 1025"
cv: /assets/cv.pdf
github_username:  PanJason
github_url: "https://github.com/PanJason"
google_scholar: "https://scholar.google.com/citations?hl=en&user=decthuIAAAAJ"
linkedin: "https://www.linkedin.com/in/yueyang-pan-167a221a4/"
wechat: pyyjason
blog: "/blog"
profile_image: "/assets/images/profile.jpeg"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections for publications
collections:
  publications:
    output: false

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
